-- =========================================
-- BASE DE DATOS AURA GLOW
-- Estructura (DDL)
-- =========================================

-- =========================================
-- TABLA: users
-- =========================================
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    apellido TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    foto_perfil TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    rol TEXT NOT NULL DEFAULT 'cliente',
    CONSTRAINT users_rol_check CHECK (rol IN ('cliente', 'admin'))
);

-- =========================================
-- TABLA: products
-- =========================================
CREATE TABLE products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    precio NUMERIC(10,2) NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0,
    categoria TEXT,
    imagen_url TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT products_precio_check CHECK (precio >= 0),
    CONSTRAINT products_stock_check CHECK (stock >= 0)
);

-- =========================================
-- TABLA: favorites
-- =========================================
CREATE TABLE favorites (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),

    CONSTRAINT unique_user_product_favorite UNIQUE (user_id, product_id),
    CONSTRAINT fk_favorites_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_favorites_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE CASCADE
);

-- =========================================
-- TABLA: cart_items
-- =========================================
CREATE TABLE cart_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT cart_items_quantity_check CHECK (quantity > 0),
    CONSTRAINT cart_items_user_id_product_id_key UNIQUE (user_id, product_id),
    CONSTRAINT cart_items_user_id_fkey
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT cart_items_product_id_fkey
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE CASCADE
);